label: 'Seneste indhold'
description: 'Seneste indhold.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Udf√∏r
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      fields:
        changed:
          separator: ', '
      title: 'Seneste indhold'
      empty:
        area_text_custom:
          content: 'No content available.'
      use_more_text: Mere
  block_1:
    display_title: Blok
