label: 'Brugerdefineret blokbibliotek'
description: 'Find og håndtér brugerdefinerede blokke.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Udfør
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
      fields:
        info:
          label: Beskrivelse
          separator: ', '
        type:
          label: Bloktype
          separator: ', '
        changed:
          label: Updated
        operations:
          label: Operations
      filters:
        info:
          expose:
            label: Beskrivelse
        type:
          expose:
            label: Bloktype
      title: 'Brugerdefineret blokbibliotek'
      empty:
        area_text_custom:
          content: 'Der er ingen tilpassede blokke tilgængeligt.'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: 'Brugerdefineret blokbibliotek'
